### ISSUE TITLE
No Work

### ISSUE THREAD

**Issue by Tarif7** [RahilBadshah/Language_Translator#1]
Hello Bro, When i change Hindi to English then this app will no translate properly. Especially if I speech.

**Comment by RahilBadshah** [comment]
Does it getting perfect words which you spoke?

**Comment by Tarif7** [comment]
Yes. It works if I write hand but it doesn't work when I speak. Only show Hindi. not translate English.

**Comment by RahilBadshah** [comment]
### Try to changing in onActivityResult method in MainActivity.java file.

Replace this line ``translate_hin(et_1.getText().toString().trim());`` with 
``if (flag)
                    translate_hin(et_1.getText().toString().trim());
                else translate_eng(et_1.getText().toString().trim());``
Or you can get latest commit in which I've solved this issue. 
And after that tell me if it's solved or not.

**Comment by Tarif7** [comment]
Yes Bro, now its work well. Thank you

**Comment by RahilBadshah** [comment]
Thanks for reporting this issue and keep supporting.

**Comment by Tarif7** [comment]
You are welcome. Bro, can you add more future like translate text to share option, History, favorite and also drawer navigation.

**Comment by RahilBadshah** [comment]
Ya will see about it because of my busy schedule I can't guarantee you but maybe share and speak feature will come soon and if you need navigation drawer code then it's already there in my repo you can check it out

**Comment by Tarif7** [comment]
Ok Bro, I will wait.

**Comment by Tarif7** [comment]
Hello bro, How are you?  How is going translate app  share and speak feature? I am still wait .
