### ISSUE TITLE
Complete APK file

### ISSUE THREAD

**Issue by cutiemahi** [RahilBadshah/Language_Translator#2]
Hi Rahil,
Could you please share with me the combined error free apk file of the above java code. It means a lot to me 
Regards Mahi ^•^

**Comment by cutiemahi** [comment]
@RahilBadshah  Help!!!!!

**Comment by RahilBadshah** [comment]
You can build apk from this code it's totally error free

**Comment by cutiemahi** [comment]
Can you please do it for me

**Comment by cutiemahi** [comment]
I tried it is showing some error
Plz

**Comment by cutiemahi** [comment]
@RahilBadshah

**Comment by cutiemahi** [comment]
@RahilBadshah

**Comment by RahilBadshah** [comment]
Ping me on telegram because it's working fine. 
https://t.me/Badshah_01

**Comment by cutiemahi** [comment]
Will you send me their?

**Comment by RahilBadshah** [comment]
Ya currently I can't commit this new change on git

**Comment by cutiemahi** [comment]
Ok
